### ISSUE TITLE
error in entity2id

### ISSUE THREAD

**Issue by lucky-dreamer-nn** [xhuang31/KEQA_WSDM19#3]
I use the embedding data which is downloaded from "https://www.dropbox.com/s/o5hd8lnr5c0l6hj/KGembed.zip", I found that not every tail entity in SimpleQuestions can get an id from the entity2id.txt, that is to say, entity2id.txt does not contain all entities in SimpleQuestions. Do you know why?

**Comment by xhuang31** [comment]
Thanks for your interest. Yes, you are right. Not every head and tail entity in SimpleQuestions is included in entity2id.txt. There are three reasons.

1. Not all the entities have been included in FB2M or FB5M. FB2M or FB5M are just subsets of Freebase.

2. In question answering, we don't know the head and tail entities of the questions. Otherwise, it is cheating. What we could do is to try the best to guess all possible entities.

3. FB2M or FB5M is too large to perform knowledge graph embedding on the 16GB GPU. Thus, we use a heuristic method to select partial entities.
